runtime: python311
service: ocr-api
instance_class: F2
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6
env_variables:
  MAX_FILE_SIZE_BYTES: "10485760"
  RATE_LIMIT_REQUESTS: "60"
  CACHE_TTL_SECONDS: "600"
